### PR TITLE
Fix black screen

### PR DESCRIPTION
**Pull request by alyssarosenzweig**

### CODE REVIEW

**Comment by alyssarosenzweig** [comment]
Er, wait, this is shadowing a larger issue. Closing this PR till I figure out the correct solution.

**Comment by my2iu** [comment]
Oh yeah, there's a bug in the OpenFL's Assets.hx with regards to loading bitmaps more than once. There's a

```
image = preload;
width = width;
height = height;
```

or something like that. It should be changed to

```
__fromImage(preload);
```

or something like that.

**Comment by alyssarosenzweig** [comment]
@my2iu I figured as much. _Two_ bugs then.

The first is that setting crossOrigin="anonymous" seems to break some browsers.

The others, I guess, is this. Still trying to figure out how to implement this correctly.

**Comment by alyssarosenzweig** [comment]
Got it. Is this a known bug?

**Comment by alyssarosenzweig** [comment]
To anyone trying to build this themselves: I've documented my patches here: https://github.com/bobbybee/scratch-flash/issues/1

**Comment by my2iu** [comment]
I haven't had the time yet to go through their bug reports to see if they are duplicates, and if not, generate patches for them. I'll go do that later this afternoon.

**Comment by my2iu** [comment]
I've submitted some of the changes to OpenFL and had them merged. I didn't submit the crossOrigin patch. I think it's only needed for Safari. Unfortunately, I don't have any Apple devices, so I can't test it and I don't really understand what the fix does, so I wouldn't know how to file a bug for it. Could you do that?

**Comment by alyssarosenzweig** [comment]
@my2iu

I have the crossOrigin bug on Firefox on GNU/Linux.

**Pull request closed without merging**
